<package format="3">
  <name>map</name>
  <version>0.0.0</version>
  <description>Minefield map visualization</description>
  <maintainer email="you@example.com">Ahmed</maintainer>
  <license>MIT</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
</package>
