set(_CATKIN_CURRENT_PACKAGE "orocos_kdl")
set(orocos_kdl_VERSION "1.5.1")
set(orocos_kdl_MAINTAINER "Ruben Smits <ruben.smits@intermodalics.eu>")
set(orocos_kdl_PACKAGE_FORMAT "3")
set(orocos_kdl_BUILD_DEPENDS "eigen")
set(orocos_kdl_BUILD_EXPORT_DEPENDS )
set(orocos_kdl_BUILDTOOL_DEPENDS "catkin")
set(orocos_kdl_BUILDTOOL_EXPORT_DEPENDS )
set(orocos_kdl_EXEC_DEPENDS "catkin" "eigen" "pkg-config")
set(orocos_kdl_RUN_DEPENDS "catkin" "eigen" "pkg-config")
set(orocos_kdl_TEST_DEPENDS "cppunit")
set(orocos_kdl_DOC_DEPENDS "doxygen")
set(orocos_kdl_URL_WEBSITE "http://wiki.ros.org/orocos_kdl")
set(orocos_kdl_URL_BUGTRACKER "")
set(orocos_kdl_URL_REPOSITORY "")
set(orocos_kdl_DEPRECATED "")